#logging:
#  level:
#    org:
#      apache:
#        http: debug
services:
  brewery:
    scheme: http
    host: localhost
    port: 8081
    baseContext: api
    version: v1
    endpoints:
      createBeer: beers/new
      getBeerById: beers/{beerId}
      updateBeerById: beers/{beerId}
      deleteBeerById: beers/{beerId}
      createCustomer: customers/new
      getCustomerById: customers/{customerId}
      updateCustomerById: customers/{customerId}
      deleteCustomerById: customers/{customerId}

logging:
  level:
    org.apache.http: debug

#logging:
#  level:
#    web: debug

rest-template:
  maxTotalConnections: 100
  defaultMaxTotalConnections: 20
  connectionRequestTimeout: 3000
  socketTimeout: 3000